language: r
env:
  global:
    - NOT_CRAN="true"
warnings_are_errors: true
apt_packages:
- pgf
- libudunits2-dev
- libnetcdf-dev
r_packages:
- covr
r_github_packages:
- sgibb/MALDIquant
r_binary_packages:
- testthat
- knitr
- XML
- base64enc
- digest
after_success:
- Rscript -e 'library(covr);codecov()'
notifications:
  email:
    on_success: change
    on_failure: change
