language: r
warnings_are_errors: true

apt_packages:
  - libudunits2-dev
  - libnetcdf-dev

r_github_packages:
  - jimhester/covr

r_binary_packages:
  - testthat
  - knitr
  - XML
  - base64enc
  - digest

after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
