language: r
sudo: false
cache: packages
warnings_are_errors: true

addons:
  apt:
    packages:
      - libudunits2-dev
      - libnetcdf-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'covr::codecov()'

r:
#  - oldrel
  - release
  - devel

notifications:
  email:
    on_success: change
    on_failure: change
